# Generated by Django 5.0.7 on 2024-07-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_dish_description_dish_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('items', models.JSONField()),
                ('full_details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
